### ISSUE TITLE
Button focus is lost on reload

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/old-website#18]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43648146/95941993-bc2fc180-0dff-11eb-864e-0bdc0140e33c.gif)

Edit: Also, clicking somewhere on the screen loses the focus of the button

**Comment by ch374n** [comment]
Hey daksh, can I work on this issue ?

**Comment by Daksh777** [comment]
Yeah, please do @ch374n
