### ISSUE TITLE
Make gallery section symmetrical for mobile users

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/old-website#25]
Need to figure out a way to display all the images in a symmetrical way and fix the issues with portrait images,
![image](https://user-images.githubusercontent.com/43648146/106146366-9a82fc00-619c-11eb-9e33-d1aeb034814c.png)

**Comment by velitasali** [comment]
what do you mean by symmetrical, could you give an example?

**Comment by Daksh777** [comment]
> what do you mean by symmetrical, could you give an example?

The images are not centred, there is a lot more space on the left side as compared to the right. The images in portrait mode are also not looking good, they are not in the same grid size as compared to the horizontal one

**Comment by velitasali** [comment]
https://github.com/Daksh777/website/commit/af465e884417d224423dd3a0bba16a06c014d442 should fix this issue :)

**Comment by Daksh777** [comment]
Thanks a ton!
